name: AWS SCP Deploy

on:
  push:
    branches:
      - main

jobs:
  Build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Setup-node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Checkout Repo.
        uses: actions/checkout@v4
      - name: exec build command.
        run: npm run build
      - name: Set-up ssh dir.
        run: mkdir ~/.ssh.
      - name: Set-up ssh-key file.
        run: echo "${{ secrets.SSH_KEY }}">~/.ssh/.pem
      - name: exec scp command.
        run: scp -i "~/.ssh/.pem" -r "./dist/*" ${{secrets.SSH_USER}}@${{secrets.DEPLOY_HOST}}:${{secrets.DEPLOY_DIR}}